// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/courses/create": {
    params: {};
  };
  "/courses/create/lessons": {
    params: {};
  };
  "/courses/create/lessons/:lessonId/edit": {
    params: {
      "lessonId": string;
    };
  };
  "/courses/create/exercises/:exerciseId/edit": {
    params: {
      "exerciseId": string;
    };
  };
  "/courses/create/speaking/:exerciseId/edit": {
    params: {
      "exerciseId": string;
    };
  };
  "/courses": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signup" | "/forgot-password" | "/dashboard" | "/settings" | "/courses/create" | "/courses/create/lessons" | "/courses/create/lessons/:lessonId/edit" | "/courses/create/exercises/:exerciseId/edit" | "/courses/create/speaking/:exerciseId/edit" | "/courses";
  };
  "auth/Login/Login.tsx": {
    id: "auth/Login/Login";
    page: "/";
  };
  "auth/Login/SignUp.tsx": {
    id: "auth/Login/SignUp";
    page: "/signup";
  };
  "auth/Login/ForgotPassword.tsx": {
    id: "auth/Login/ForgotPassword";
    page: "/forgot-password";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/courseInfo.tsx": {
    id: "routes/courseInfo";
    page: "/courses/create";
  };
  "routes/courseCreate.tsx": {
    id: "routes/courseCreate";
    page: "/courses/create/lessons";
  };
  "routes/LessonBuilder.tsx": {
    id: "routes/LessonBuilder";
    page: "/courses/create/lessons/:lessonId/edit";
  };
  "routes/ExerciseCreate.tsx": {
    id: "routes/ExerciseCreate";
    page: "/courses/create/exercises/:exerciseId/edit";
  };
  "routes/SpeakingCreate.tsx": {
    id: "routes/SpeakingCreate";
    page: "/courses/create/speaking/:exerciseId/edit";
  };
  "routes/CoursesManagement.tsx": {
    id: "routes/CoursesManagement";
    page: "/courses";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "auth/Login/Login": typeof import("./app/auth/Login/Login.tsx");
  "auth/Login/SignUp": typeof import("./app/auth/Login/SignUp.tsx");
  "auth/Login/ForgotPassword": typeof import("./app/auth/Login/ForgotPassword.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/courseInfo": typeof import("./app/routes/courseInfo.tsx");
  "routes/courseCreate": typeof import("./app/routes/courseCreate.tsx");
  "routes/LessonBuilder": typeof import("./app/routes/LessonBuilder.tsx");
  "routes/ExerciseCreate": typeof import("./app/routes/ExerciseCreate.tsx");
  "routes/SpeakingCreate": typeof import("./app/routes/SpeakingCreate.tsx");
  "routes/CoursesManagement": typeof import("./app/routes/CoursesManagement.tsx");
};